title: DbGate
# description: >
#   Opensource database manager for MySQL, PostgreSQL and SQL Server

paginate: 5
paginate_path: "/blog/page:num"

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - kramdown-parser-gfm

exclude: 
  - Gemfile
  - clean-theme.gemspec
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# include: 
#   - node_modules/node_modules/bulma-carousel/dist

livereload: true

sass:
  style: compressed
  source_dir: _sass


markdown: kramdown
highlighter: rouge

collections:
  features: 
    output: true
  database: 
    output: true
